#!/usr/bin/env node
// dual-review — post anchored findings as GitHub review threads, then submit (or leave pending)
// a COMMENT review whose body carries the summary and any findings that could not be anchored.
//
//   post-review.mjs <cacheDir> [--submit]

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { POSTED_MARKER } from "./findings.mjs";

const argv = process.argv.slice(2);
const cacheDir = argv[0] && !argv[0].startsWith("-") ? path.resolve(argv[0]) : null;
const submit = argv.includes("--submit");
if (!cacheDir) {
  console.error("usage: post-review.mjs <cacheDir> [--submit]");
  process.exit(2);
}

const meta = JSON.parse(fs.readFileSync(path.join(cacheDir, "meta.json"), "utf8"));
if (meta.mode !== "pr") {
  console.error("dual-review: posting requires a PR review (mode is not 'pr').");
  process.exit(1);
}
const data = JSON.parse(fs.readFileSync(meta.paths.findings, "utf8"));

function gh(args) {
  return execFileSync("gh", args, {
    cwd: meta.repoRoot,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

function graphql(query, variables) {
  const args = ["api", "graphql", "-f", `query=${query}`];
  for (const [name, value] of Object.entries(variables)) {
    args.push(typeof value === "number" ? "-F" : "-f", `${name}=${value}`);
  }
  let response;
  try {
    response = JSON.parse(gh(args));
  } catch (error) {
    const stderr = String(error.stderr ?? "").trim();
    const stdout = String(error.stdout ?? "").trim();
    let detail = stderr || error.message;
    try {
      const parsed = JSON.parse(stdout);
      if (parsed.errors?.length) detail = parsed.errors.map((e) => e.message).join("; ");
    } catch {}
    throw new Error(detail);
  }
  if (response.errors?.length) throw new Error(response.errors.map((e) => e.message).join("; "));
  return response;
}

const SINGLE_COMMENT =
  "mutation($prId: ID!, $body: String!, $path: String!, $line: Int!) { addPullRequestReviewThread(input: { pullRequestId: $prId, body: $body, path: $path, line: $line, side: RIGHT }) { thread { id } } }";
const RANGE_COMMENT =
  "mutation($prId: ID!, $body: String!, $path: String!, $line: Int!, $startLine: Int!) { addPullRequestReviewThread(input: { pullRequestId: $prId, body: $body, path: $path, line: $line, startLine: $startLine, side: RIGHT, startSide: RIGHT }) { thread { id } } }";
const SUBMIT =
  "mutation($prId: ID!, $body: String) { submitPullRequestReview(input: { pullRequestId: $prId, event: COMMENT, body: $body }) { pullRequestReview { id url } } }";
const BODY_ONLY =
  "mutation($prId: ID!, $body: String) { addPullRequestReview(input: { pullRequestId: $prId, event: COMMENT, body: $body }) { pullRequestReview { id url } } }";

const footer = `_Generated by dual-review — Claude + ${meta.gptModel}._\n${POSTED_MARKER}`;

function lineCommentBody(finding) {
  const lines = [`**${finding.severity}: ${finding.title}**`];
  if (finding.impact) lines.push("", `Impact: ${finding.impact}`);
  if (finding.recommendation) lines.push("", `Recommendation: ${finding.recommendation}`);
  lines.push("", footer);
  return lines.join("\n");
}

function reviewBody(unanchored) {
  const visible = data.findings.filter((f) => f.bucket !== "already-raised");
  const sev = data.counts.severity;
  const lines = [
    "## Dual review summary",
    "",
    `Findings: ${visible.length} (blocker ${sev.blocker}, major ${sev.major}, minor ${sev.minor}, nit ${sev.nit})`,
  ];
  if (data.summary) lines.push("", data.summary);
  if (visible.length > 0) {
    lines.push("", "### Findings", "");
    for (const f of visible) lines.push(`- **${f.severity}: ${f.title}**${f.source !== "unknown" ? ` _(${f.source})_` : ""}`);
  }
  if (unanchored.length > 0) {
    lines.push("", "### Findings not anchored to the diff", "", "No line comment could be attached to these findings.");
    for (const f of unanchored) {
      lines.push("", `- **${f.severity}: ${f.title}**`);
      if (f.location && f.location.toLowerCase() !== "n/a") lines.push(`  - Location: \`${f.location}\``);
      if (f.impact) lines.push(`  - Impact: ${f.impact}`);
      if (f.recommendation) lines.push(`  - Recommendation: ${f.recommendation}`);
    }
  }
  lines.push("", footer);
  return lines.join("\n");
}

const lineComments = data.findings.filter((f) => f.bucket === "line");
const unanchored = data.findings.filter((f) => f.bucket === "unanchored");
const skipped = data.findings.filter((f) => f.bucket === "already-raised");

if (lineComments.length === 0 && unanchored.length === 0) {
  console.log(`Nothing to post${skipped.length ? ` (${skipped.length} already raised)` : ""}.`);
  process.exit(0);
}

const prId = gh(["pr", "view", String(meta.prNumber), "-R", meta.repo, "--json", "id", "--jq", ".id"]);
let posted = 0;
let failed = 0;
for (const finding of lineComments) {
  const variables = {
    prId,
    body: lineCommentBody(finding),
    path: finding.file,
    line: finding.line,
    ...(finding.startLine === null ? {} : { startLine: finding.startLine }),
  };
  try {
    graphql(finding.startLine === null ? SINGLE_COMMENT : RANGE_COMMENT, variables);
    posted += 1;
    console.log(`Posted ${finding.file}:${finding.line}`);
  } catch (error) {
    failed += 1;
    console.error(`Failed to post ${finding.file}:${finding.line}: ${error.message}`);
  }
}
console.log(`Posted ${posted} line comment(s), ${failed} failed, ${skipped.length} skipped as already raised.`);

let state = "pending";
let reviewUrl = null;
if (submit) {
  if (posted > 0) {
    const response = graphql(SUBMIT, { prId, body: reviewBody(unanchored) });
    reviewUrl = response.data?.submitPullRequestReview?.pullRequestReview?.url ?? null;
    state = "submitted";
  } else if (unanchored.length > 0) {
    const response = graphql(BODY_ONLY, { prId, body: reviewBody(unanchored) });
    reviewUrl = response.data?.addPullRequestReview?.pullRequestReview?.url ?? null;
    state = "submitted";
  } else {
    state = "nothing-to-submit";
  }
  console.log(state === "submitted" ? `Submitted comment review${reviewUrl ? `: ${reviewUrl}` : "."}` : "No comments were posted; nothing to submit.");
} else if (posted > 0) {
  console.log(`Left the review pending on PR #${meta.prNumber}; submit it from GitHub when ready.`);
} else {
  state = "nothing-posted";
  console.log("No comments were posted; no pending review was created.");
}

fs.writeFileSync(
  meta.paths.postResult,
  JSON.stringify({ at: new Date().toISOString(), posted, failed, skipped: skipped.length, unanchored: unanchored.length, state, reviewUrl }, null, 2),
);
